server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://product-service:8081/
          predicates:
            - Path=/product/**
        - id: customer
          uri: http://customer-service:8082/
          predicates:
            - Path=/customer/**
        - id: account
          uri: http://account-service:8083/
          predicates:
            - Path=/account/**
        - id: credit
          uri: http://credit-service:8084/
          predicates:
            - Path=/credit/**