version: '3.9'
services:
  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    image: config-server:latest
    ports:
      - '8888:8888'
    networks:
      - bootcamp
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: ./discovery-service/Dockerfile
    image: discovery-service:latest
    ports:
      - '9091:9091'
    networks:
      - bootcamp
    depends_on:
      - config-server
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    image: api-gateway:latest
    ports:
      - '8080:8080'
    networks:
      - bootcamp
    depends_on:
      - config-server
      - discovery-service
  mongodb-service:
    image: mongo:5.0
    ports:
      - '27017:27017'
    container_name: mongodb-service
    volumes:
      - ./db/:/data/db
    networks:
      - bootcamp
  redis-server:
    image: redis
    ports:
      - '6379:6379'
    container_name: redis-server
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - bootcamp
  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    depends_on:
      - mongodb-service
      - config-server
      - discovery-service
    image: product-service:latest
    ports:
      - '8081:8081'
    networks:
      - bootcamp
  customer-service:
    container_name: customer-service
    build:
      context: .
      dockerfile: ./customer-service/Dockerfile
    depends_on:
      - mongodb-service
      - config-server
      - discovery-service
    image: customer-service:latest
    ports:
      - '8082:8082'
    networks:
      - bootcamp
  account-service:
    container_name: account-service
    build:
      context: .
      dockerfile: ./account-service/Dockerfile
    depends_on:
      - mongodb-service
      - config-server
      - discovery-service
    image: account-service:latest
    ports:
      - '8083:8083'
    networks:
      - bootcamp
  credit-service:
    container_name: credit-service
    build:
      context: .
      dockerfile: ./credits-service/Dockerfile
    depends_on:
      - mongodb-service
      - config-server
      - discovery-service
    image: credit-service:latest
    ports:
      - '8084:8084'
    networks:
      - bootcamp
  report-service:
    container_name: report-service
    build:
      context: .
      dockerfile: ./report-service/Dockerfile
    depends_on:
      - config-server
      - discovery-service
    image: report-service:latest
    ports:
      - '8085:8085'
    networks:
      - bootcamp
  card-service:
    container_name: card-service
    build:
      context: .
      dockerfile: ./card-service/Dockerfile
    depends_on:
      - mongodb-service
      - config-server
      - discovery-service
    image: card-service:latest
    ports:
      - '8086:8086'
    networks:
      - bootcamp
  wallet-service:
    container_name: wallet-service
    build:
      context: .
      dockerfile: ./wallet-service/Dockerfile
    depends_on:
      - mongodb-service
      - config-server
      - discovery-service
    image: wallet-service:latest
    ports:
      - '8087:8087'
    networks:
      - bootcamp
  wallet-transaction-service:
    container_name: wallet-transaction-service
    build:
      context: .
      dockerfile: ./wallet-transaction-service/Dockerfile
    depends_on:
      - mongodb-service
      - redis-server
      - config-server
      - discovery-service
    image: wallet-transaction-service:latest
    ports:
      - '8088:8088'
    networks:
      - bootcamp
networks:
  bootcamp:
    driver: bridge