version: '3.9'
services:
  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    image: config-server:latest
    ports:
      - '8888:8888'
    networks:
      - bootcamp
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: ./discovery-service/Dockerfile
    image: discovery-service:latest
    ports:
      - '9091:9091'
    networks:
      - bootcamp
    depends_on:
      - config-server
networks:
  bootcamp:
    driver: bridge