version: '3.9'
services:
  mongodb-service:
    image: mongo:5.0
    ports:
      - 27017:27017
    container_name: mongodb-service
    volumes:
      - ./db/:/data/db
  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb-service
    image: product-service:latest
    ports:
      - 8080:8080