version: '3.9'
services:
  mongodb-service:
    image: mongo:5.0
    ports:
      - 27018:27017
    container_name: mongodb-service
    volumes:
      - ./db/:/data/db
  account-service:
    container_name: account-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb-service
    image: account-service:latest
    ports:
      - 8082:8080