version: '3.9'
services:
  mongodb-service:
    image: mongo:5.0
    ports:
      - 27020:27017
    container_name: mongodb-service
    volumes:
      - ./db/:/data/db
  customer-service:
    container_name: customer-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb-service
    image: customer-service:latest
    ports:
      - 8081:8080